# .github/workflows/call-reusable-workflow.yml
name: Use Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  use_shared_workflow:
    uses: ambatibhargavi/shared-workflows/.github/workflows/reusable-workflow.yml@main
    with:
      greeting: "Hello"
      name: "Ambati"
